spring.application.name=LovAI Backend API
spring.datasource.url=${DB_URL:jdbc:postgresql://db.bqvmudyaaflksxwjbsxy.supabase.co:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:RK3ovhI3BgOyBq22}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vanlinh280104@gmail.com
spring.mail.password=jlfpanvinnfrnlig
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.type.preferred_enum_type=postgres_enum

# JWT Configuration
jwt.secret=lovai-secret-key-2024-very-secure-key-for-jwt-token-generation
jwt.expiration=86400000

# Supabase config
supabase.url=https://bqvmudyaaflksxwjbsxy.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdm11ZHlhYWZsa3N4d2pic3h5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODUzNTYwMSwiZXhwIjoyMDc0MTExNjAxfQ.mi06GYRXlY7iiBu-nmzCFG8WnWfPzr_wqRegew9_Amw
supabase.bucket=media-lovai

# Firebase config
firebase.config.path=lovai-d5bd9-firebase-adminsdk-fbsvc-1ce77c3b86.json